name: 'Rediacc Elite Services'
description: 'Start Rediacc core services (web server, API, SQL Server) for CI/CD testing'
author: 'Rediacc'

branding:
  icon: 'database'
  color: 'blue'

inputs:
  keep-alive:
    description: 'Skip automatic cleanup to keep services running (default: false)'
    required: false
    default: 'false'
  ci-mode:
    description: 'Enable CI/TEST mode (bypasses email and captcha validation)'
    required: false
    default: 'true'

outputs:
  api-url:
    description: 'API endpoint URL'
    value: ${{ steps.setup.outputs.api-url }}
  sql-connection:
    description: 'SQL Server connection string (for testing)'
    value: ${{ steps.setup.outputs.sql-connection }}

runs:
  using: 'composite'
  steps:
    - name: Start Services
      id: setup
      shell: bash
      working-directory: ${{ github.action_path }}/..
      run: |
        echo "=== CI_MODE Debug ==="
        echo "inputs.ci-mode: '${{ inputs.ci-mode }}'"
        export CI_MODE="${{ inputs.ci-mode }}"
        echo "CI_MODE after export: '$CI_MODE'"
        echo "====================="
        action/ci-start.sh

    - name: Cleanup Services
      if: always() && inputs.keep-alive != 'true'
      shell: bash
      working-directory: ${{ github.action_path }}/..
      run: action/ci-cleanup.sh
