name: 'Rediacc Elite Services'
description: 'Start Rediacc core services (nginx, API, SQL Server) for CI/CD testing'
author: 'Rediacc'

branding:
  icon: 'database'
  color: 'blue'

outputs:
  api-url:
    description: 'API endpoint URL'
    value: ${{ steps.setup.outputs.api-url }}
  sql-connection:
    description: 'SQL Server connection string (for testing)'
    value: ${{ steps.setup.outputs.sql-connection }}

runs:
  using: 'composite'
  steps:
    - name: Start Services
      id: setup
      shell: bash
      working-directory: ${{ github.action_path }}/..
      run: action/ci-start.sh

    - name: Cleanup Services
      if: always()
      shell: bash
      working-directory: ${{ github.action_path }}/..
      run: action/ci-cleanup.sh
